/**
 * IDX broker code constants for bandar detection algorithm.
 *
 * PLATFORM_BROKERS — retail trading platforms excluded from bandar candidacy
 * because their volume represents aggregated retail orders, not institutional positioning.
 *
 * BROKER_NAMES — full IDX member list (90 brokers, March 2026).
 */

/** Retail platform brokers — always excluded from kandidat_bandar classification */
export const PLATFORM_BROKERS = new Set(['CC', 'YP', 'XL', 'XC', 'PD'])

/** Full IDX broker code → short name mapping */
export const BROKER_NAMES: Record<string, string> = {
  XC: 'Ajaib',
  PP: 'Aldiracita',
  YO: 'Amantara',
  ID: 'Anugerah',
  SH: 'Artha Sekuritas',
  DX: 'Bahana',
  SQ: 'BCA Sekuritas',
  AR: 'Binaartha',
  GA: 'BNC Sekuritas',
  NI: 'BNI Sekuritas',
  OD: 'BRI Danareksa',
  RF: 'Buana Capital',
  ZR: 'Bumiputera',
  YU: 'CGS-CIMB',
  KI: 'Ciptadana',
  KZ: 'CLSA',
  PF: 'Danasakti',
  II: 'Danatama',
  DP: 'DBS Vickers',
  TS: 'Dwidana Sakti',
  ES: 'Ekokapital',
  SA: 'Elit Sukses',
  BS: 'Equity Sekuritas',
  AO: 'Erdikha Elit',
  EL: 'Evergreen',
  PC: 'FAC Sekuritas',
  FO: 'Forte Global',
  AF: 'Harita Kencana',
  HP: 'Henan Putihrai',
  RB: 'INA Sekuritas',
  IU: 'Indo Capital',
  IH: 'Indo Harvest',
  PD: 'Indo Premier',
  IC: 'Integrity Capital',
  BF: 'Inti Fikasa',
  IT: 'Inti Teladan',
  IN: 'Investindo Nusantara',
  BK: 'J.P. Morgan',
  DU: 'KAF Sekuritas',
  AI: 'Kay Hian',
  CP: 'KB Valbury',
  HD: 'KGI Sekuritas',
  AG: 'Kiwoom',
  BQ: 'Korea Investment',
  TF: 'Laba Sekuritas',
  YJ: 'Lotus Andalan',
  RX: 'Macquarie',
  PI: 'Magenta Kapital',
  DD: 'Makindo',
  CC: 'Mandiri Sekuritas',
  ZP: 'Maybank',
  CD: 'Mega Capital',
  MU: 'Minna Padi',
  YP: 'Mirae Asset',
  EP: 'MNC Sekuritas',
  OK: 'Net Sekuritas',
  XA: 'NH Korindo',
  TP: 'OCBC Sekuritas',
  AP: 'Pacific Sekuritas',
  PG: 'Panca Global',
  GR: 'Panin Sekuritas',
  PS: 'Paramitra Alfa',
  KK: 'Phillip Sekuritas',
  AT: 'Phintraco',
  PO: 'Pilarmas Investindo',
  RO: 'Pluang',
  RG: 'Profindo',
  LS: 'Reliance',
  DR: 'RHB Sekuritas',
  IF: 'Samuel Sekuritas',
  MG: 'Semesta Indovest',
  AH: 'Shinhan',
  DH: 'Sinarmas',
  XL: 'Stockbit',
  AZ: 'Sucor Sekuritas',
  AD: 'Sukadana Prima',
  SS: 'Supra Sekuritas',
  SF: 'Surya Fajar',
  LG: 'Trimegah',
  BR: 'Trust Sekuritas',
  QA: 'Tuntun Sekuritas',
  AK: 'UBS',
  BB: 'Verdhana',
  MI: 'Victoria',
  AN: 'Wanteg',
  FZ: 'Waterfront',
  GI: 'Webull',
  YB: 'Yakin Bertumbuh',
  FS: 'Yuanta',
  RS: 'Yulie Sekuritas',
}
